spring.application.name=ecogasto

spring.datasource.url=jdbc:postgresql://localhost:5432/ecogasto_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

ecogasto.jwt.secret=EcoGasto-UPC-2026-clave-secreta-para-firmar-jwt
ecogasto.jwt.expiration-ms=28800000

ecogasto.ia.api-key=${GEMINI_API_KEY:}
ecogasto.ia.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

springdoc.swagger-ui.path=/swagger-ui.html
